name: 'CD (firtool)'

on:
  workflow_dispatch:
    inputs:
      should-create-pr:
        description: |
          An optional script to decide whether to open the Pull Request or not.
          The script must accept a single positional argument (the new CIRCT
          version). The script is only run when there is a new version of CIRCT.  A
          return value of 0 means "open the PR". A return value of 1 means "do not
          open the PR". Any other return value will cause the action to exit with
          an error. Note, the default value 'true' is the shell built-in, not a
          boolean value.
        type: string
        default: 'exit 0 $1'

jobs:
  cd-circt:
    name: 'Check Version, Create PR'
    runs-on: ubuntu-22.04
    steps:
      - name: 'jackkoenig/update-circt'
        uses: jackkoenig/update-circt@should-create-pr
        with:
          user: chiselbot
          email: chiselbot@users.noreply.github.com
          pr-labels: |
            Dependency Update
          pr-reviewers: |
            jackkoenig
          should-create-pr: inputs.should-create-pr
